ipap_calculator:
    resource: "@IpapCalculatorBundle/Controller/"
    type:     annotation
    prefix:   /

ipap_ejemplo_asistencia:
    resource: "@IpapEjemploAsistenciaBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
