ipap_ejemplo_asistencia:
    resource: "@IpapEjemploAsistenciaBundle/Controller/"
    type:     annotation
    prefix:   /

ipap_calculator:
    resource: "@IpapCalculatorBundle/Controller/"
    type:     annotation
    prefix:   /

